extern void stockASM();
extern void overkartASM();
extern void runTextureScroll();
extern void runWaterVertex();
extern void runDisplayScreen();
extern void loadTextureScrollTranslucent();
extern void copyCourseTable();
extern void hsTableSet();
extern void stockTableSet();
extern void setSong();
extern void setTempo();
extern void setASM();
extern void setEcho();
extern void setSky();
extern void setWater();
extern void loadHeaderOffsets();
extern void loadHotSwap();
extern void loadMinimap();
extern void setLabel();
extern void setBanners();
extern void setPreviews();
extern void swapHS();
extern void previewRefresh();
extern void SetCourseNames(bool custom);
extern void SetCloudType(char CloudType);