.align 0x10
.importobj "library\LibraryVariables.o"
.align 0x10
.importobj "library\MarioKart3D.o"
.align 0x10
.importobj "library\MarioKartMemory.o"
.align 0x10
.importobj "library\MarioKartObjects.o"
.align 0x10
.importobj "library\MarioKartStats.o"
.align 0x10
.importobj "Library\PlayerEffects.o"
.align 0x10
.importobj "library\SharedFunctions.o"
.align 0x10
.importobj "Library\CustomLevels.o"
.align 0x10
.importobj "Library\OKBehaviors.o"