.align 0x10
.importobj "../library/LibraryVariables.o"
.align 0x10
.importobj "../library/MarioKart3D.o"
.align 0x10
.importobj "../library/MarioKartObjects.o"
.align 0x10
.importobj "../library/MarioKartMenu.o"
.align 0x10
.importobj "../library/MarioKartStats.o"
.align 0x10
.importobj "../library/PlayerEffects.o"
.align 0x10
.importobj "../library/SharedFunctions.o"
.align 0x10
.importobj "../library/CustomLevels.o"
.align 0x10
.importobj "../library/CustomSurfaces.o"
.align 0x10
.importobj "../library/CustomSounds.o"
.align 0x10
.importobj "../library/MusicControl.o"
.align 0x10
.importobj "../library/OKBehaviors.o"
.align 0x10
.importobj "../library/PlayerChecks.o"
.align 0x10
.importobj "../library/OKCustomObjects.o"