extern void Draw3DRacer();
extern void DisplayRedCoin(void *Camera, void *Object);
extern void DisplayObject(void *Camera, void *Object);
extern int CollideObject(void* Car, void* Coin);
extern int RedCoinCollide(void* Car, void* Coin);
extern void DisplayCoinSprite();
extern void DisplayAfterEffects();
extern void loadCoin();
extern void DrawOKObjects();
extern void CheckOKObjects();
extern void ClearOKObject(short ObjectID);
extern short FindOKObject();
extern bool TestCollideBox(float SourcePosition[], float SourceSize[], short SourceAngle[], float TargetPosition[], float TargetRadius);
extern bool TestCollideSphere(float SourcePosition[], float SourceRadius, float TargetPosition[], float TargetRadius);
